# Generated by Django 6.0.6 on 2026-07-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_discount_amount_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
