# Generated by Django 6.0.6 on 2026-07-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
